export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_ERROR = 'FETCH_POKEMON_ERROR';
export const FETCH_POKEMON_DETAILS = 'FETCH_POKEMON_DETAILS';
export const FETCH_POKEMON_DETAILS_SUCCESS = 'FETCH_POKEMON_DETAILS_SUCCESS';
export const FETCH_POKEMON_SPECIES = 'FETCH_POKEMON_SPECIES';
export const FETCH_POKEMON_SPECIES_SUCCESS = 'FETCH_POKEMON_SPECIES_SUCCESS';
